# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

##  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [3]:
ls

CONTRIBUTING.md  Data/  index.ipynb  LICENSE.md  README.md

In [6]:
# Your code here - Load the file
import pandas as pd
df = pd.read_excel('Data/Zipcode_Demos.xlsx')

In [9]:
# Your code here - Perform exploratory data analysis
df.head()
df

,0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Average Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
48,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
49,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
50,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
51,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
53,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
54,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
55,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
56,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [14]:
# What is going on with this data set? Anything unusual?
df1 = pd.read_excel('Data/Zipcode_Demos.xlsx', header=1,nrows =46, usecols=1)
df1

                     Average Statistics  Unnamed: 1
0                                   NaN       0.000
1                     JURISDICTION NAME   10005.800
2                    COUNT PARTICIPANTS       9.400
3                          COUNT FEMALE       4.800
4                        PERCENT FEMALE       0.404
5                            COUNT MALE       4.600
6                          PERCENT MALE       0.396
7                  COUNT GENDER UNKNOWN       0.000
8                PERCENT GENDER UNKNOWN       0.000
9                    COUNT GENDER TOTAL       9.400
10                 PERCENT GENDER TOTAL      80.000
11               COUNT PACIFIC ISLANDER       0.000
12             PERCENT PACIFIC ISLANDER       0.000
13                COUNT HISPANIC LATINO       2.000
14              PERCENT HISPANIC LATINO       0.105
15                COUNT AMERICAN INDIAN       0.000
16              PERCENT AMERICAN INDIAN       0.000
17             COUNT ASIAN NON HISPANIC       3.600
18           PERCENT ASIAN NON HISPANIC       0.437
19             COUNT WHITE NON HISPANIC       0.800
20           PERCENT WHITE NON HISPANIC       0.036
21             COUNT BLACK NON HISPANIC       2.600
22           PERCENT BLACK NON HISPANIC       0.181
23                COUNT OTHER ETHNICITY       0.400
24              PERCENT OTHER ETHNICITY       0.040
25              COUNT ETHNICITY UNKNOWN       0.000
26            PERCENT ETHNICITY UNKNOWN       0.000
27                COUNT ETHNICITY TOTAL       9.400
28              PERCENT ETHNICITY TOTAL      79.900
29       COUNT PERMANENT RESIDENT ALIEN       0.500
30     PERCENT PERMANENT RESIDENT ALIEN       0.061
31                     COUNT US CITIZEN       8.900
32                   PERCENT US CITIZEN       0.739
33           COUNT OTHER CITIZEN STATUS       0.000
34         PERCENT OTHER CITIZEN STATUS       0.000
35         COUNT CITIZEN STATUS UNKNOWN       0.000
36       PERCENT CITIZEN STATUS UNKNOWN       0.000
37           COUNT CITIZEN STATUS TOTAL       9.400
38         PERCENT CITIZEN STATUS TOTAL      80.000
39     COUNT RECEIVES PUBLIC ASSISTANCE       2.300
40   PERCENT RECEIVES PUBLIC ASSISTANCE       0.151
41    COUNT NRECEIVES PUBLIC ASSISTANCE       7.100
42  PERCENT NRECEIVES PUBLIC ASSISTANCE       0.649
43      COUNT PUBLIC ASSISTANCE UNKNOWN       0.000
44    PERCENT PUBLIC ASSISTANCE UNKNOWN       0.000
45        COUNT PUBLIC ASSISTANCE TOTAL       9.400

In [16]:
# Your code here - Clean up the data set
df2 = pd.read_excel('Data/Zipcode_Demos.xlsx', header=48)
df2

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10001,44,22,0.50,22,0.50,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
2,10003,1,1,1.00,0,0.00,0,0,1,100,...,1,100,0,0.00,1,1.00,0,0,1,100
3,10004,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,10005,2,2,1.00,0,0.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100
5,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0.00,6,1.00,0,0,6,100
6,10007,1,0,0.00,1,1.00,0,0,1,100,...,1,100,1,1.00,0,0.00,0,0,1,100
7,10009,2,0,0.00,2,1.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100
8,10010,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
9,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0.00,3,1.00,0,0,3,100

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [27]:

!ls Data/

ACS_16_5YR_B24011_metadata.csv	Yelp_Reviews_Corrupt.csv
ACS_16_5YR_B24011_with_ann.csv	Yelp_Selected_Businesses.xlsx
ACS2012_2016_PUMS_README.pdf	Zipcode_Demos.csv
bp.txt				Zipcode_Demos.xlsx

In [53]:
#Hint: here's a useful programming pattern to use.
rows_to_skip = []
df3 = None
success = False
while(not success):
    try:
        #do something
        df3 = pd.read_csv("Data/Yelp_Reviews_Corrupt.csv",skiprows=rows_to_skip)
        success = True
        
    except Exception as e:
        #handle your exception e
        rows_to_skip.append(int(str(e).split()[-3][:-1])-1)
df3

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0,HkYqGb0Gplmmk-xlHTRBoA,1,The score should be negative. Its HORRIBLE. Th...,0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0,RgqWdZA4xR023iP3T6jVfA,5,I went there twice and I am pretty happy with ...,0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0,51RHs_V_fjuistnuKxNpEg,5,Finally! After trying many Mexican restaurants...,0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0,alI_kRKyEHfdHibYGgtJbw,1,I have to write a review on the Fractured Prun...,0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0,85DRIjwPJOTb4q0qOlBstw,1,I wish i could tell you all about the food but...,1,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0,GbiLIKmQPVCBtdNkTVdVSA,5,Wonderful! One of my favorite places. BBQ is e...,0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0,UaHgsL0xS4UnJ_iKqeOk_w,5,The price is about the same as Quizinos. The s...,0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0,c4zzAD1S6721Fh-acCBy-g,4,The food was ok. You get a lot of food for the...,0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0,TTBwocu2mvqJFJrwmJN0Sw,5,The staff were friendly and helpful. The food ...,1,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0,-CresnnXQSHrQ85Ogm-Pqw,5,The staff were very helpful. We painted potter...,0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0,U04YgYr4PiGUxB46J4xapg,2,Limited vegetarian options. Ordered Greek sala...,0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0,s9cpVj40VR_yl0lXbZQe6w,5,I trust my vehicles here. Comparable prices. M...,0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0,AJ0IglpYAp2D0daOlVGIdg,1,This place doesn't even deserve 1 star. Horrib...,18,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0,5D_MsAJHrMa8QKkpE3g1Sg,5,The butter burger was cooked perfectly and jui...,0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0,5bWN_IN8MQGjJ6_ZIXffDw,5,Best location ever! I love love love the manag...,0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0,RW_mYzHYfdqn6g7xVgIcKg,4,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0,SLA1YP9doUc8h-6Kd34QmA,1,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0,qxPiEGIHy5xyVy78avH5Rg,4,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0,q6ij-nz5d_hvdjuelho1pQ,5,Better service and much better prices than the...,0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0,66FSK2J1uHJqVI1Z8QiFGw,4,I love how they have no rice sushi options. Th...,0,Yy_iGXxLpL6tYDQoE-6XVg
...,...,...,...,...,...,...,...,...,...,...
4005,+kiki burger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,Cons:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,-there isn't one in San Diego!,1,M8KZG9AxSaaJCyRZrHVXzg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4008,Everything else on the menu was enjoyable,with very good portion sizes - small enough t...,the rolls come in 4's,so you can try more than one roll. Another pl...,which I've never seen at AYCE sushi before,along with other jellos (black current and li...,mango pudding and a chef's special.,NaN,NaN,NaN
4009,While pricey,$24.99 on the weekends,I would say that its worth it.,0,hJulW1s6tOBr2NXD9nAoMQ,NaN,NaN,NaN,NaN,NaN
4010,506,RJxkhoGxTsz545_sTlDdFA,0,2014-07-01,0,cEQ9swcZ_L0GMCKI0UtItQ,2,Pad thai (beef),NaN,NaN
4011,- The beef used was tough and chewy. The pad t...,0,UGW-9bbBEB3eP1o6mWD_WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4012,While Bamburger offers a decent take-out menu,we chose to enjoy their small,but friendly sidewalk patio,right in the middle of restaurant row at Yong...,natural wood and lots of greenery complimenti...,talkative and more than willing to explain th...,as there are many,and recommend some personal favourites.,NaN,NaN
4013,Starting off with drinks,Bamburger serves beer,wine,and old-fashioned Stewart's soda,but what is a burger joint without milkshakes...,including the usual vanilla and chocolate sus...,as well a special flavour each day for the ni...,NaN,NaN,NaN
4014,Bamburger serves up great burgers,fries and shakes at a fairly good price,although if you go a little overboard with th...,you might quickly end up with a $20 burger,without realizing it. The service was friendl...,and the atmosphere was very comfortable and n...,NaN,NaN,NaN,NaN
4015,If you are hunting for a real deal on a burger,Bamburger might not be what you are looking for,but if you are more on the adventurous side,and want to have fun creating your own burger...,Bamburger will deliver.,8,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN
4016,4674,4KfDcE9iU2isFpoaKeDpgw,0,2012-06-14,0,rFH9iSvRmdm5LtDdsYwwpA,5,Great place to take your kids and interesting ...,0,9gYbRvijurhrnC6yPRlaUw
4017,3440,nW45ez1L6U4PsYhV1BTrGQ,0,2012-05-19,0,abStF7f3_IyfZmOP82baZQ,5,H&F Jewellery is amazing!,NaN,NaN
4018,I had given my husband some ideas of engagemen...,a friend of ours recommended H&F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4019,The customer service here is great - they are ...,attentive,honest and the prices are very reasonable! My...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4020,We went back for our wedding bands and I worke...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4021,We've recommended 5 other friends to H&F - the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,Go to H&F for all your jewellery needs - you w...,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4023,4812,e13SEvJud_vgeDR_doL4sQ,0,2013-03-01,0,lUV1KEm4cl4mluSEFharFQ,4,We loved the food. The service was good and we...,0,NW6gHZ8PlYl1STK1A1Ixeg
4024,564,5XYR6doRa5Nj1JMfSDei6A,1,2016-06-14,0,xlGJkxoIBl8XH8wVsPZpnw,5,Always great friendly service and fresh baked ...,NaN,NaN
4025,Highly recommend the custard cakes they are th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4026,The rice flour cake is also really good and a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4027,The bean cakes are great here too! orange,almond,and a few others I have tried are all good.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4028,Can't go wrong with Nova Era,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4029,3458,aLcFhMe6DDJ430zelCpd2A,0,2013-10-02,0,kwiEG_KCpDB6aK5fTSM7iw,2,We were expecting amazing Thai food after all ...,NaN,NaN
4030,This was disappointing.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4031,First off,it was really awkward sitting on the benches ...,as people walked past us while to wait for ou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4032,Second,when we were seated,it was so loud. It felt like we were in a hig...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4033,Finally - Food was mediocre. I was extremely d...,but it wasn't flavourful.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4034,Wasn't worth the hype,unfortunately.,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df3

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0,HkYqGb0Gplmmk-xlHTRBoA,1,The score should be negative. Its HORRIBLE. Th...,0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0,RgqWdZA4xR023iP3T6jVfA,5,I went there twice and I am pretty happy with ...,0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0,51RHs_V_fjuistnuKxNpEg,5,Finally! After trying many Mexican restaurants...,0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0,alI_kRKyEHfdHibYGgtJbw,1,I have to write a review on the Fractured Prun...,0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0,85DRIjwPJOTb4q0qOlBstw,1,I wish i could tell you all about the food but...,1,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0,GbiLIKmQPVCBtdNkTVdVSA,5,Wonderful! One of my favorite places. BBQ is e...,0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0,UaHgsL0xS4UnJ_iKqeOk_w,5,The price is about the same as Quizinos. The s...,0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0,c4zzAD1S6721Fh-acCBy-g,4,The food was ok. You get a lot of food for the...,0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0,TTBwocu2mvqJFJrwmJN0Sw,5,The staff were friendly and helpful. The food ...,1,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0,-CresnnXQSHrQ85Ogm-Pqw,5,The staff were very helpful. We painted potter...,0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0,U04YgYr4PiGUxB46J4xapg,2,Limited vegetarian options. Ordered Greek sala...,0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0,s9cpVj40VR_yl0lXbZQe6w,5,I trust my vehicles here. Comparable prices. M...,0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0,AJ0IglpYAp2D0daOlVGIdg,1,This place doesn't even deserve 1 star. Horrib...,18,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0,5D_MsAJHrMa8QKkpE3g1Sg,5,The butter burger was cooked perfectly and jui...,0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0,5bWN_IN8MQGjJ6_ZIXffDw,5,Best location ever! I love love love the manag...,0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0,RW_mYzHYfdqn6g7xVgIcKg,4,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0,SLA1YP9doUc8h-6Kd34QmA,1,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0,qxPiEGIHy5xyVy78avH5Rg,4,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0,q6ij-nz5d_hvdjuelho1pQ,5,Better service and much better prices than the...,0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0,66FSK2J1uHJqVI1Z8QiFGw,4,I love how they have no rice sushi options. Th...,0,Yy_iGXxLpL6tYDQoE-6XVg
...,...,...,...,...,...,...,...,...,...,...
4005,+kiki burger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,Cons:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,-there isn't one in San Diego!,1,M8KZG9AxSaaJCyRZrHVXzg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4008,Everything else on the menu was enjoyable,with very good portion sizes - small enough t...,the rolls come in 4's,so you can try more than one roll. Another pl...,which I've never seen at AYCE sushi before,along with other jellos (black current and li...,mango pudding and a chef's special.,NaN,NaN,NaN
4009,While pricey,$24.99 on the weekends,I would say that its worth it.,0,hJulW1s6tOBr2NXD9nAoMQ,NaN,NaN,NaN,NaN,NaN
4010,506,RJxkhoGxTsz545_sTlDdFA,0,2014-07-01,0,cEQ9swcZ_L0GMCKI0UtItQ,2,Pad thai (beef),NaN,NaN
4011,- The beef used was tough and chewy. The pad t...,0,UGW-9bbBEB3eP1o6mWD_WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4012,While Bamburger offers a decent take-out menu,we chose to enjoy their small,but friendly sidewalk patio,right in the middle of restaurant row at Yong...,natural wood and lots of greenery complimenti...,talkative and more than willing to explain th...,as there are many,and recommend some personal favourites.,NaN,NaN
4013,Starting off with drinks,Bamburger serves beer,wine,and old-fashioned Stewart's soda,but what is a burger joint without milkshakes...,including the usual vanilla and chocolate sus...,as well a special flavour each day for the ni...,NaN,NaN,NaN
4014,Bamburger serves up great burgers,fries and shakes at a fairly good price,although if you go a little overboard with th...,you might quickly end up with a $20 burger,without realizing it. The service was friendl...,and the atmosphere was very comfortable and n...,NaN,NaN,NaN,NaN
4015,If you are hunting for a real deal on a burger,Bamburger might not be what you are looking for,but if you are more on the adventurous side,and want to have fun creating your own burger...,Bamburger will deliver.,8,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN
4016,4674,4KfDcE9iU2isFpoaKeDpgw,0,2012-06-14,0,rFH9iSvRmdm5LtDdsYwwpA,5,Great place to take your kids and interesting ...,0,9gYbRvijurhrnC6yPRlaUw
4017,3440,nW45ez1L6U4PsYhV1BTrGQ,0,2012-05-19,0,abStF7f3_IyfZmOP82baZQ,5,H&F Jewellery is amazing!,NaN,NaN
4018,I had given my husband some ideas of engagemen...,a friend of ours recommended H&F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4019,The customer service here is great - they are ...,attentive,honest and the prices are very reasonable! My...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4020,We went back for our wedding bands and I worke...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4021,We've recommended 5 other friends to H&F - the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,Go to H&F for all your jewellery needs - you w...,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4023,4812,e13SEvJud_vgeDR_doL4sQ,0,2013-03-01,0,lUV1KEm4cl4mluSEFharFQ,4,We loved the food. The service was good and we...,0,NW6gHZ8PlYl1STK1A1Ixeg
4024,564,5XYR6doRa5Nj1JMfSDei6A,1,2016-06-14,0,xlGJkxoIBl8XH8wVsPZpnw,5,Always great friendly service and fresh baked ...,NaN,NaN
4025,Highly recommend the custard cakes they are th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4026,The rice flour cake is also really good and a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4027,The bean cakes are great here too! orange,almond,and a few others I have tried are all good.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4028,Can't go wrong with Nova Era,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4029,3458,aLcFhMe6DDJ430zelCpd2A,0,2013-10-02,0,kwiEG_KCpDB6aK5fTSM7iw,2,We were expecting amazing Thai food after all ...,NaN,NaN
4030,This was disappointing.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4031,First off,it was really awkward sitting on the benches ...,as people walked past us while to wait for ou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4032,Second,when we were seated,it was so loud. It felt like we were in a hig...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4033,Finally - Food was mediocre. I was extremely d...,but it wasn't flavourful.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4034,Wasn't worth the hype,unfortunately.,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
rows_to_skip

[2330,
 2339,
 2340,
 2342,
 2348,
 2349,
 2351,
 2357,
 2358,
 2378,
 2380,
 2381,
 2383,
 2385,
 2387,
 2388,
 2391,
 2392,
 2393,
 2406,
 2426,
 2429,
 2437,
 2438,
 2439,
 2440,
 2441,
 2444,
 2445,
 2472,
 2473,
 2474,
 2484,
 2486,
 2487,
 2495,
 2503,
 2504,
 2506,
 2520,
 2521,
 2524,
 2532,
 2547,
 2560,
 2562,
 2563,
 2564,
 2570,
 2573,
 2574,
 2576,
 2582,
 2583,
 2620,
 2621,
 2630,
 2631,
 2632,
 2635,
 2639,
 2640,
 2673,
 2675,
 2705,
 2707,
 2711,
 2713,
 2714,
 2736,
 2745,
 2751,
 2752,
 2753,
 2757,
 2760,
 2761,
 2766,
 2768,
 2770,
 2784,
 2786,
 2809,
 2816,
 2830,
 2834,
 2836,
 2840,
 2841,
 2847,
 2884,
 2900,
 2901,
 2902,
 2921,
 2922,
 2923,
 2930,
 2939,
 2954,
 2957,
 2970,
 2971,
 2994,
 2997,
 2998,
 3006,
 3018,
 3034,
 3063,
 3065,
 3068,
 3078,
 3079,
 3085,
 3091,
 3105,
 3116,
 3119,
 3121,
 3124,
 3125,
 3126,
 3151,
 3158,
 3168,
 3220,
 3233,
 3234,
 3252,
 3256,
 3273,
 3282,
 3287,
 3288,
 3289,
 3307,
 3308,
 3309,
 3324,
 3328,
 3337,
 3338,
 3343,
 3349,
 3360,
 3361,
 3374,
 3375,
 3376,
 3377,
 3383,
 3384,
 3385,
 3402,
 3403,
 3404,
 3412,
 3413,
 3421,
 3422,
 3434,
 3436,
 3437,
 3438,
 3441,
 3442,
 3466,
 3467,
 3469,
 3470,
 3473,
 3474,
 3475,
 3477,
 3478,
 3479,
 3497,
 3511,
 3512,
 3513,
 3514,
 3515,
 3518,
 3520,
 3521,
 3522,
 3528,
 3529,
 3530,
 3531,
 3536,
 3537,
 3539,
 3558,
 3560,
 3564,
 3565,
 3566,
 3567,
 3590,
 3591,
 3594,
 3614,
 3626,
 3633,
 3640,
 3651,
 3652,
 3655,
 3656,
 3657,
 3671,
 3712,
 3722,
 3724,
 3725,
 3727,
 3732,
 3733,
 3734,
 3739,
 3748,
 3754,
 3755,
 3761,
 3767,
 3775,
 3796,
 3798,
 3804,
 3805,
 3832,
 3843,
 3844,
 3863,
 3876,
 3883,
 3886,
 3888,
 3902,
 3907,
 3916,
 3917,
 3918,
 3925,
 3926,
 3927,
 3945,
 3952,
 3953,
 3954,
 3955,
 3956,
 3958,
 3966,
 3974,
 3975,
 3980,
 3993,
 3996,
 4003,
 4013,
 4014,
 4019,
 4034,
 4040,
 4041,
 4049,
 4050,
 4051,
 4053,
 4054,
 4063,
 4065,
 4066,
 4067,
 4068,
 4069,
 4071,
 4089,
 4090,
 4106,
 4118,
 4119,
 4120,
 4121,
 4125,
 4126,
 4129,
 4130,
 4131,
 4137,
 4139,
 4169,
 4172,
 4179,
 4196,
 4213,
 4241,
 4248,
 4249,
 4256,
 4257,
 4258,
 4260,
 4266,
 4267,
 4276,
 4281,
 4282,
 4284,
 4285,
 4287,
 4304,
 4307,
 4309,
 4311,
 4312,
 4313,
 4323,
 4328,
 4329,
 4335,
 4351,
 4352,
 4374,
 4376,
 4377,
 4382,
 4408,
 4417,
 4418,
 4420,
 4442,
 4444,
 4449,
 4451,
 4454,
 4455,
 4463,
 4486,
 4493,
 4494,
 4502,
 4503,
 4504,
 4526,
 4562,
 4563,
 4564,
 4576,
 4577,
 4588,
 4604,
 4605,
 4606,
 4607,
 4608,
 4625,
 4631,
 4640,
 4657,
 4658,
 4659,
 4664,
 4669,
 4689,
 4694,
 4721,
 4728,
 4729,
 4740,
 4741,
 4763,
 4764,
 4774,
 4775,
 4776,
 4780,
 4781,
 4783,
 4785,
 4786,
 4787,
 4800,
 4801,
 4802,
 4803,
 4805,
 4807,
 4808,
 4824,
 4832,
 4838,
 4839,
 4853,
 4855,
 4858,
 4859,
 4860,
 4861,
 4862,
 4863,
 4864,
 4865,
 4869,
 4877,
 4879,
 4880,
 4890,
 4895,
 4896,
 4908,
 4910,
 4911,
 4917,
 4918,
 4921,
 4923,
 4924,
 4934,
 4966,
 4974,
 4975,
 4976,
 4990,
 5017,
 5029,
 5030,
 5031,
 5032,
 5034,
 5035,
 5047,
 5049,
 5062,
 5071,
 5079,
 5080,
 5081,
 5084,
 5086,
 5092,
 5094,
 5095,
 5097,
 5098,
 5099,
 5110,
 5117,
 5118,
 5138,
 5139,
 5140,
 5142,
 5150,
 5154,
 5169,
 5174,
 5179,
 5180,
 5181,
 5187,
 5188,
 5194,
 5195,
 5197,
 5233,
 5234,
 5236,
 5237,
 5245,
 5254,
 5257,
 5266,
 5267,
 5270,
 5271,
 5276,
 5290,
 5292,
 5293,
 5294,
 5297,
 5301,
 5302,
 5303,
 5309,
 5322,
 5326,
 5328,
 5329,
 5332,
 5333,
 5334,
 5362,
 5363,
 5376,
 5377,
 5383,
 5384,
 5391,
 5393,
 5394,
 5405,
 5416,
 5427,
 5430,
 5431,
 5432,
 5433,
 5434,
 5468,
 5469,
 5471,
 5472,
 5473,
 5476,
 5487,
 5497,
 5501,
 5513,
 5531,
 5543,
 5551,
 5552,
 5562,
 5563,
 5572,
 5600,
 5608,
 5609,
 5610,
 5611,
 5615,
 5617,
 5618,
 5619,
 5631,
 5632,
 5633,
 5635,
 5636,
 5637,
 5638,
 5646,
 5647,
 5655,
 5662,
 5663,
 5665,
 5688,
 5693,
 5737,
 5742,
 5779,
 5780,
 5781,
 5788,
 5789,
 5790,
 5791,
 5814,
 5815,
 5816,
 5818,
 5835,
 5844,
 5858,
 5860,
 5862,
 5863,
 5864,
 5865,
 5868,
 5871,
 5877,
 5879,
 5883,
 5902,
 5904,
 5905,
 5909,
 5917,
 5918,
 5919,
 5937,
 5940,
 5962,
 5967,
 5968,
 5969,
 5971,
 5974,
 5987,
 5989,
 6019,
 6021,
 6022,
 6023,
 6026,
 6028,
 6035,
 6046,
 6047,
 6054,
 6055,
 6061,
 6063,
 6068,
 6070,
 6083,
 6084,
 6085,
 6108]

## Summary

Congratulations, you now practiced your pandas-importing skills!